kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "jenkins-slave-gradle-centos7"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/defcyy/s2i-springboot-gradle.git"
  strategy:
    type: "Docker"
    dockerStrategy:
      dockerfilePath: "Dockerfile.jenkins-slave"
  output:
    to:
      kind: "DockerImage"
      name: "docker-registry.default.svc:5000/ci/jenkins-slave-gradle-centos7:latest"