spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/defcyy/s2i-springboot-gradle.git"
  strategy:
    type: "Docker"
    dockerStrategy:
      dockerfilePath: "Dockerfile.jenkins-slave"
  output:
    to:
      kind: "ImageStream"
      name: "docker-registry.default.svc:5000/ci/openshift/jenkins-slave-gradle-centos7:latest"