kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "springboot-gradle-centos7"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/defcyy/s2i-springboot-gradle.git"
  strategy:
    type: "Docker"
    dockerStrategy:
      dockerfilePath: "Dockerfile"
  output:
    to:
      kind: "ImageStreamTag"
      name: "springboot-gradle-centos7:latest"

